
### index
GET localhost:8090/ping

### load
GET localhost:8090/load?img_bucket=imgsch&table_name=milvus_imgsch_tab



### download
GET localhost:8090/img/44cffb7fe6339ad06e4f046ae52fa987.jpg


### search
# curl -X POST -H "Content-Type: multipart/form-data" -F "file=@../data/bicycle.jpg" http://localhost:8090/search
POST localhost:8090/search
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="bicycle.jpg"

< ../data/bicycle.jpg
--WebAppBoundary--

###

